version: '3.4'

volumes:
    pgdata:
        driver: local

services:
    db:
        restart: always
        image: postgres:12.0-alpine
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./app:/app
        env_file:
            - dev.env
    ngrok:
        image: wernight/ngrok
        ports:
            - '4040:4040'
        env_file:
            - dev.env
        depends_on:
            - app
    redis:
        restart: always
        image: redis:6.2.1-alpine
        ports:
            - 6379:6379
    celery:
        restart: always
        build: .
        command: celery -A mail_sender worker -l INFO
        env_file:
            - dev.env
        depends_on:
            - redis
            - db
    app:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./app:/app
        ports:
            - 8000:8000
        command: >
            bash -c "python manage.py migrate --noinput || exit 1
            && python manage.py runserver 0.0.0.0:8000"
        env_file:
            - dev.env
        depends_on:
            - celery
            - db